server:
  port: 8080
  servlet:
    context-path: /

spring:
#  security:
#    user:
#      name: admin
#      password: spicy-mustard
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      continue-on-error: true
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 256MB

openAI:
  apiKey: ${API_KEY:test}